import Feed from '@/components/Feed'
import Sidebar from '@/components/Sidebar'
import Widgets from '@/components/Widgets'
import Head from 'next/head'


export default function Home({newResults,randomUserResults}) {
  return (
    <div>
      <Head>
        <title>Twitter clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex min-h-screen mx-auto">
        {/* sidebar */}

        <Sidebar />

        {/* feed */}

        <Feed />

        {/* widgets */}

        <Widgets
          newResults={newResults.articles}
          randomUserResults={randomUserResults.results}
        />

        {/* modals */}
      </main>
    </div>
  );
};



// https://saurav.tech/NewsAPI/top-headlines/category/business/Us.json

export async function getServerSideProps(){
    const newResults = await fetch("https://saurav.tech/NewsAPI/top-headlines/category/business/us.json").then((res)=>res.json());

    // who to follow section 
    const randomUserResults = await fetch(
      "https://randomuser.me/api/?results=30&inc=name,login,picture").then((res)=>res.json());
    return {
        props:{
            newResults,
            randomUserResults,
        },
    };
    
}
